from app.ai.schemas import (
    AssistantAnswerOutput,
    BrainAnswerOutput,
    BrainQueryParseOutput,
    ClauseExtractionOutput,
    ContractDocxGenerationOutput,
    ContractEditSuggestionsOutput,
    ContractMetadataOutput,
    ContractRiskOutput,
    ObligationExtractionOutput,
    PlaybookChatBuildOutput,
    PlaybookGenerationOutput,
    PlaybookRecommendationsOutput,
    PlaybookReviewOutput,
    RenewalExtractionOutput,
    SkillInfo,
    TabularCellOutput,
    TabularChatOutput,
)
from app.ai.skill import SkillSpec


class SkillRegistry:
    def __init__(self) -> None:
        self._skills: dict[str, SkillSpec] = {}

    def register(self, spec: SkillSpec) -> None:
        if spec.name in self._skills:
            raise RuntimeError(f"Duplicate AI skill registered: {spec.name}")
        if not spec.prompt_key or not spec.prompt_version:
            raise RuntimeError(f"AI skill {spec.name} is missing prompt metadata")
        self._skills[spec.name] = spec

    def get(self, name: str) -> SkillSpec:
        try:
            return self._skills[name]
        except KeyError as exc:
            raise KeyError(f"Unknown AI skill: {name}") from exc

    def all(self) -> list[SkillSpec]:
        return sorted(self._skills.values(), key=lambda spec: spec.name)

    def public_info(self) -> list[SkillInfo]:
        return [
            SkillInfo(
                name=spec.name,
                version=spec.version,
                execution_mode=spec.execution_mode,
                prompt_key=spec.prompt_key,
                prompt_version=spec.prompt_version,
                output_schema_name=spec.output_schema_name,
                required_permission=spec.required_permission,
                feature_flag=spec.feature_flag,
                enabled_by_default=spec.enabled_by_default,
                requires_citations=spec.requires_citations,
                allows_mutation=spec.allows_mutation,
            )
            for spec in self.all()
        ]


skill_registry = SkillRegistry()

for registered_spec in [
    SkillSpec(
        name="contract_metadata_extraction",
        version="1.0.0",
        description="Extract supported contract metadata with citations.",
        execution_mode="job",
        prompt_key="contract_metadata_extraction",
        prompt_version="1.0.0",
        input_model=None,
        output_model=ContractMetadataOutput,
        required_permission="contract:read",
        resource_type="contract",
        requires_citations=True,
        allows_mutation=True,
        feature_flag="feature.ai.metadata_extraction",
        enabled_by_default=True,
        max_tokens=2048,
    ),
    SkillSpec(
        name="clause_extraction",
        version="1.0.0",
        description="Extract key clauses for Contract Brain and review.",
        execution_mode="job",
        prompt_key="clause_extraction",
        prompt_version="1.0.0",
        input_model=None,
        output_model=ClauseExtractionOutput,
        required_permission="contract:read",
        resource_type="contract",
        requires_citations=True,
        allows_mutation=True,
        feature_flag="feature.ai.clause_extraction",
        enabled_by_default=True,
        max_tokens=4096,
    ),
    SkillSpec(
        name="contract_risk_assessment",
        version="1.0.0",
        description="Assess per-clause risk for the weighted contract risk score.",
        execution_mode="contract_brain",
        prompt_key="contract_risk_assessment",
        prompt_version="1.0.0",
        input_model=None,
        output_model=ContractRiskOutput,
        required_permission="contract:read",
        resource_type="contract",
        requires_citations=False,
        allows_mutation=False,
        feature_flag="feature.ai.clause_extraction",
        enabled_by_default=True,
        max_tokens=4096,
    ),
    SkillSpec(
        name="playbook_generation",
        version="1.0.0",
        description="Draft playbook rules (standard positions) from a source document.",
        execution_mode="job",
        prompt_key="playbook_generation",
        prompt_version="1.0.0",
        input_model=None,
        output_model=PlaybookGenerationOutput,
        required_permission="playbook:create",
        resource_type=None,
        requires_citations=False,
        allows_mutation=False,
        feature_flag="feature.ai.playbook_generation",
        enabled_by_default=True,
        max_tokens=8000,
    ),
    SkillSpec(
        name="playbook_chat_build",
        version="1.0.0",
        description="Conversationally build and refine a playbook draft from documents + chat.",
        execution_mode="job",
        prompt_key="playbook_chat_build",
        prompt_version="1.0.0",
        input_model=None,
        output_model=PlaybookChatBuildOutput,
        required_permission="playbook:create",
        resource_type=None,
        requires_citations=False,
        allows_mutation=False,
        feature_flag="feature.ai.playbook_chat_build",
        enabled_by_default=True,
        max_tokens=12000,
    ),
    SkillSpec(
        name="playbook_recommendations",
        version="1.0.0",
        description="Recommend playbook rule changes from real deviation/decision usage.",
        execution_mode="job",
        prompt_key="playbook_recommendations",
        prompt_version="1.0.0",
        input_model=None,
        output_model=PlaybookRecommendationsOutput,
        required_permission="playbook:create",
        resource_type=None,
        requires_citations=False,
        allows_mutation=False,
        feature_flag="feature.ai.playbook_recommendations",
        enabled_by_default=True,
        max_tokens=6000,
    ),
    SkillSpec(
        name="assistant_streaming",
        version="1.0.0",
        description="Assistant chat with contract handles, citations, and tools.",
        execution_mode="assistant",
        prompt_key="assistant_streaming",
        prompt_version="1.0.0",
        input_model=None,
        output_model=AssistantAnswerOutput,
        required_permission="assistant:use",
        resource_type=None,
        requires_citations=False,
        allows_mutation=False,
        feature_flag="feature.ai.assistant_streaming",
        enabled_by_default=True,
        max_tokens=4096,
    ),
    SkillSpec(
        name="contract_docx_generation",
        version="1.0.0",
        description="Create backend-renderable DOCX generation plans.",
        execution_mode="assistant_tool",
        prompt_key="contract_docx_generation",
        prompt_version="1.0.0",
        input_model=None,
        output_model=ContractDocxGenerationOutput,
        required_permission="contract:create",
        resource_type="contract",
        requires_citations=False,
        allows_mutation=True,
        feature_flag="feature.ai.docx_generation",
        enabled_by_default=True,
        max_tokens=16000,
    ),
    SkillSpec(
        name="contract_edit_suggestions",
        version="1.0.0",
        description="Create tracked-change-ready contract edit suggestions.",
        execution_mode="assistant_tool",
        prompt_key="contract_edit_suggestions",
        prompt_version="1.0.0",
        input_model=None,
        output_model=ContractEditSuggestionsOutput,
        required_permission="contract:redline",
        resource_type="contract",
        requires_citations=True,
        allows_mutation=True,
        feature_flag="feature.ai.edit_suggestions",
        enabled_by_default=True,
        max_tokens=16000,
    ),
    SkillSpec(
        name="obligation_extraction",
        version="1.0.0",
        description="Extract obligations with owners, due dates, recurrence, and citations.",
        execution_mode="job",
        prompt_key="obligation_extraction",
        prompt_version="1.0.0",
        input_model=None,
        output_model=ObligationExtractionOutput,
        required_permission="contract:read",
        resource_type="contract",
        requires_citations=True,
        allows_mutation=True,
        feature_flag="feature.ai.obligation_extraction",
        enabled_by_default=True,
        max_tokens=4096,
    ),
    SkillSpec(
        name="renewal_extraction",
        version="1.0.0",
        description="Extract expiration/notice dates and renewal terms with citations.",
        execution_mode="job",
        prompt_key="renewal_extraction",
        prompt_version="1.0.0",
        input_model=None,
        output_model=RenewalExtractionOutput,
        required_permission="contract:read",
        resource_type="contract",
        requires_citations=True,
        allows_mutation=True,
        feature_flag="feature.ai.renewal_extraction",
        enabled_by_default=True,
        max_tokens=2048,
    ),
    SkillSpec(
        name="contract_brain_query_parse",
        version="1.0.0",
        description="Parse a Contract Brain question into retrieval scope and filters.",
        execution_mode="contract_brain",
        prompt_key="contract_brain_query_parse",
        prompt_version="1.0.0",
        input_model=None,
        output_model=BrainQueryParseOutput,
        required_permission="assistant:use",
        resource_type=None,
        requires_citations=False,
        allows_mutation=False,
        feature_flag="feature.ai.contract_brain",
        enabled_by_default=True,
        max_tokens=1024,
    ),
    SkillSpec(
        name="contract_brain_answer",
        version="1.0.0",
        description="Answer a Contract Brain question from retrieved, permission-filtered context with citations.",
        execution_mode="contract_brain",
        prompt_key="contract_brain_answer",
        prompt_version="1.0.0",
        input_model=None,
        output_model=BrainAnswerOutput,
        required_permission="assistant:use",
        resource_type="contract",
        requires_citations=True,
        allows_mutation=False,
        feature_flag="feature.ai.contract_brain",
        enabled_by_default=True,
        max_tokens=3072,
    ),
    SkillSpec(
        name="tabular_cell_extraction",
        version="1.0.0",
        description="Answer one tabular-review column question for one contract, with citations.",
        execution_mode="job",
        prompt_key="tabular_cell_extraction",
        prompt_version="1.0.0",
        input_model=None,
        output_model=TabularCellOutput,
        required_permission="assistant:use_ai_tools",
        resource_type="contract",
        requires_citations=True,
        allows_mutation=False,
        feature_flag="feature.ai.tabular_review",
        enabled_by_default=True,
        max_tokens=2048,
    ),
    SkillSpec(
        name="tabular_review_chat",
        version="1.0.0",
        description="Answer questions over a completed tabular review using cell data and citations.",
        execution_mode="tabular_review",
        prompt_key="tabular_review_chat",
        prompt_version="1.0.0",
        input_model=None,
        output_model=TabularChatOutput,
        required_permission="assistant:use",
        resource_type=None,
        requires_citations=False,
        allows_mutation=False,
        feature_flag="feature.ai.tabular_review",
        enabled_by_default=True,
        max_tokens=2048,
    ),
    SkillSpec(
        name="playbook_review",
        version="1.0.0",
        description="Compare a contract against a governed playbook version and return cited deviations.",
        execution_mode="playbook_run",
        prompt_key="playbook_review",
        prompt_version="1.0.0",
        input_model=None,
        output_model=PlaybookReviewOutput,
        required_permission="playbook:run",
        resource_type="contract",
        requires_citations=True,
        allows_mutation=True,
        feature_flag="feature.ai.playbook_review",
        enabled_by_default=True,
        max_tokens=4096,
    ),
]:
    skill_registry.register(registered_spec)
