"""Word's automatic clause numbers must survive extraction.

A numbered paragraph stores only "item of list N at level L" — Word counts the
visible "2.1" while laying out the page. `paragraph.text` therefore returns
`Confidential Information means...` with no number anywhere in it, and
`split_blocks` finds clause boundaries by exactly that number at a line start.
An eleven-clause contract arrived as ONE block: no clause separable, no
section citable by its number, and every downstream consumer — clause
extraction, obligations, embeddings, redlines — working from a single
undifferentiated slab.

The loss was invisible because every document in the database was generated by
AEGIS itself, which writes its numbers as literal text.
"""

from io import BytesIO

from docx import Document
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

from app.contract_files.blocks import split_blocks
from app.contract_files.text_extraction import extract_text

DOCX_MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"


def _el(tag: str, **attrs):
    element = OxmlElement(tag)
    for name, value in attrs.items():
        element.set(qn(name), str(value))
    return element


def _define_list(document, levels, *, num_id="90", abstract_id="900", start_override=None):
    """Add a multilevel numbering definition, the way a real contract template
    carries one. `levels` is [(numFmt, lvlText), ...] deepest-last."""
    numbering = document.part.numbering_part.element
    abstract = _el("w:abstractNum", **{"w:abstractNumId": abstract_id})
    for ilvl, (fmt, text) in enumerate(levels):
        lvl = _el("w:lvl", **{"w:ilvl": ilvl})
        lvl.append(_el("w:start", **{"w:val": 1}))
        lvl.append(_el("w:numFmt", **{"w:val": fmt}))
        lvl.append(_el("w:lvlText", **{"w:val": text}))
        abstract.append(lvl)
    numbering.insert(0, abstract)
    num = _el("w:num", **{"w:numId": num_id})
    num.append(_el("w:abstractNumId", **{"w:val": abstract_id}))
    if start_override is not None:
        override = _el("w:lvlOverride", **{"w:ilvl": 0})
        override.append(_el("w:startOverride", **{"w:val": start_override}))
        num.append(override)
    numbering.append(num)


def _numbered(document, text, ilvl, *, num_id="90"):
    paragraph = document.add_paragraph(text)
    num_pr = OxmlElement("w:numPr")
    num_pr.append(_el("w:ilvl", **{"w:val": ilvl}))
    num_pr.append(_el("w:numId", **{"w:val": num_id}))
    paragraph._p.get_or_add_pPr().append(num_pr)
    return paragraph


def _extract(document) -> str:
    buffer = BytesIO()
    document.save(buffer)
    return extract_text(buffer.getvalue(), mime_type=DOCX_MIME, filename="c.docx").text


# --- the defect --------------------------------------------------------------


def test_an_auto_numbered_contract_splits_into_its_real_clauses():
    """The failure this file exists for. Without the numbers the splitter has
    no boundary to find and the whole agreement is one block, so a question
    about the liability cap retrieves the entire contract or nothing."""
    document = Document()
    _define_list(document, [("decimal", "%1."), ("decimal", "%1.%2")])
    _numbered(document, "DEFINITIONS", 0)
    _numbered(document, "Confidential Information means non-public information.", 1)
    _numbered(document, "TERM", 0)
    _numbered(document, "This Agreement continues for three years.", 1)

    text = _extract(document)
    assert "1. DEFINITIONS" in text
    assert "2. TERM" in text
    assert len(split_blocks(text)) == 4


def test_a_deeper_level_restarts_under_each_parent():
    """Numbering is counted, not stored: if deeper levels are not reset when a
    parent increments, section 2's first sub-clause is cited as 2.3 — a
    plausible-looking number for a clause that does not exist."""
    document = Document()
    _define_list(document, [("decimal", "%1."), ("decimal", "%1.%2")])
    _numbered(document, "ONE", 0)
    _numbered(document, "first", 1)
    _numbered(document, "second", 1)
    _numbered(document, "TWO", 0)
    _numbered(document, "third", 1)

    assert "2.1 third" in _extract(document)


def test_numbering_carried_by_the_style_is_found():
    """Word's own "List Number" defines its numbering in styles.xml, not on the
    paragraph, and a template's house style inherits it through basedOn.
    Reading only the paragraph returns nothing for every such clause — which
    is most of them in professionally drafted paper."""
    document = Document()
    document.add_paragraph("Governing law is the State of New York.", style="List Number")
    document.add_paragraph("Notices go to the addresses in Schedule A.", style="List Number")

    text = _extract(document)
    assert "1. Governing law" in text
    assert "2. Notices" in text


# --- formats -----------------------------------------------------------------


def test_a_lettered_sub_clause_is_not_rendered_as_a_digit():
    """"(a)" and "(b)" are how sub-clauses are cited in the contracts this
    handles; rendering them 1 and 2 cites a clause by a number it never had."""
    document = Document()
    _define_list(document, [("decimal", "%1."), ("lowerLetter", "(%2)")])
    _numbered(document, "INDEMNITY", 0)
    _numbered(document, "third party claims", 1)
    _numbered(document, "regulatory penalties", 1)

    text = _extract(document)
    assert "(a) third party claims" in text
    assert "(b) regulatory penalties" in text


def test_an_article_prefix_in_the_definition_is_kept():
    """lvlText is a template, not a number — "Article %1" must come out as
    "Article IV", which is also what makes the clause splitter recognise it."""
    document = Document()
    _define_list(document, [("upperRoman", "Article %1")])
    for heading in ("SCOPE", "FEES", "TERM", "LIABILITY"):
        _numbered(document, heading, 0)

    assert "Article IV LIABILITY" in _extract(document)


def test_a_restarted_list_starts_where_word_restarts_it():
    """A schedule that restarts at 1 via startOverride would otherwise continue
    the body's sequence and number every schedule clause wrongly."""
    document = Document()
    _define_list(document, [("decimal", "%1.")], start_override=5)
    _numbered(document, "FEES", 0)

    assert "5. FEES" in _extract(document)


# --- what must NOT change ----------------------------------------------------


def test_a_document_without_numbering_is_untouched():
    """The regression guard that matters most: offsets are computed from this
    text, so a stray prefix on an unnumbered paragraph would shift every stored
    citation in the corpus. Every document currently in the database is
    AEGIS-generated and writes its numbers as literal text."""
    document = Document()
    document.add_paragraph("1. TERM. This Agreement begins on the Effective Date.")
    document.add_paragraph("")
    document.add_paragraph("2. FEES. Fees are payable within thirty days.")

    assert _extract(document) == (
        "1. TERM. This Agreement begins on the Effective Date.\n"
        "\n"
        "2. FEES. Fees are payable within thirty days."
    )


def test_a_bulleted_list_gets_no_marker():
    """A bullet carries no clause identity, and the marker would sit inside
    every citation quoted back from those lines."""
    document = Document()
    _define_list(document, [("bullet", "•")])
    _numbered(document, "onshore support", 0)

    assert _extract(document) == "onshore support"


def test_a_missing_level_definition_does_not_break_extraction():
    """Client paper is full of malformed numbering. Text extraction feeds the
    entire pipeline, so an unexpected shape must cost the number, not the
    document."""
    document = Document()
    _define_list(document, [("decimal", "%1.")])
    _numbered(document, "orphaned sub-clause", 3)  # no lvl 3 defined
    _numbered(document, "SCOPE", 0)

    text = _extract(document)
    assert "orphaned sub-clause" in text
    assert "1. SCOPE" in text
